/**
 * Converts standard HTML tags generated by the TipTap editor
 * into markdown format, utilizing the browser's DOMParser.
 */
export function convertHtmlToMarkdown(html: string): string {
    const parser = new DOMParser();
    const doc = parser.parseFromString(html, 'text/html');
    
    function walk(node: Node): string {
        if (node.nodeType === Node.TEXT_NODE) {
            return node.textContent || '';
        }
        
        if (node.nodeType !== Node.ELEMENT_NODE) {
            return '';
        }
        
        const el = node as HTMLElement;
        const tagName = el.tagName.toUpperCase();
        
        let childrenVal = '';
        el.childNodes.forEach(child => {
            childrenVal += walk(child);
        });
        
        switch (tagName) {
            case 'H1':
                return `\n# ${childrenVal}\n`;
            case 'H2':
                return `\n## ${childrenVal}\n`;
            case 'H3':
                return `\n### ${childrenVal}\n`;
            case 'H4':
                return `\n#### ${childrenVal}\n`;
            case 'H5':
                return `\n##### ${childrenVal}\n`;
            case 'H6':
                return `\n###### ${childrenVal}\n`;
            case 'P':
                return `\n${childrenVal}\n`;
            case 'STRONG':
            case 'B':
                return `**${childrenVal}**`;
            case 'EM':
            case 'I':
                return `*${childrenVal}*`;
            case 'CODE':
                if (el.parentElement?.tagName.toUpperCase() === 'PRE') {
                    return childrenVal;
                }
                return `\`${childrenVal}\``;
            case 'PRE':
                return `\n\`\`\`\n${childrenVal}\n\`\`\`\n`;
            case 'BLOCKQUOTE':
                return `\n> ${childrenVal.trim().replace(/\n/g, '\n> ')}\n`;
            case 'UL':
                return `\n${childrenVal}\n`;
            case 'OL':
                return `\n${childrenVal}\n`;
            case 'LI': {
                const parent = el.parentElement;
                if (parent?.tagName.toUpperCase() === 'OL') {
                    const index = Array.from(parent.children).indexOf(el) + 1;
                    return `${index}. ${childrenVal}\n`;
                }
                return `- ${childrenVal}\n`;
            }
            case 'HR':
                return `\n---\n`;
            case 'BR':
                return `\n`;
            default:
                return childrenVal;
        }
    }
    
    return walk(doc.body).trim().replace(/\n{3,}/g, '\n\n');
}

/**
 * Triggers a client-side file download of a text blob.
 */
export function triggerDownload(filename: string, content: string, mimeType: string) {
    const blob = new Blob([content], { type: `${mimeType};charset=utf-8;` });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.setAttribute("download", filename);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
}
